project:
  type: website

website:
  title: "Aswin van Woudenberg"
  favicon: favicon.png
  description: "A blog on machine learning and coding"
  navbar:
    collapse: false
    right:
      - icon: github
        href: https://github.com/afvanwoudenberg
      - icon: linkedin
        href: https://linkedin.com/in/afvanwoudenberg
      - icon: rss
        href: index.xml
format:
  html:
    theme: [simplex, theme.scss]
    page-layout: article
    css: styles.css
execute:
  freeze: auto
