project:
  type: website

website:
  title: "Aswin van Woudenberg"
  favicon: favicon.png
  site-url: https://www.aswinvanwoudenberg.com
  description: "A blog on machine learning and coding"
  navbar:
    collapse: false
    right:
      - icon: github
        href: https://github.com/afvanwoudenberg
      - icon: linkedin
        href: https://linkedin.com/in/afvanwoudenberg
      - icon: rss
        href: index.xml
format:
  html:
    include-in-header: gtm_code_head.html
    include-before-body: gtm_code_body.html
    theme: [simplex, theme.scss]
    page-layout: article
    css: styles.css
comments:
  giscus:
    repo: afvanwoudenberg/afvanwoudenberg.github.io
execute:
  freeze: auto
